### PR TITLE
Update Istanbul to nyc for code coverage

### PR DESCRIPTION
**Pull request by Nmargolis**
### Context
#697 
tl;dr istanbul is deprecated and breaks on some features of es6, like destructuring.
nyc is the maintained version 2.0 of istanbul

### Summary of Changes
- [x] Remove istanbul as a dependency
- [x] Add nyc as a dependency
- [x] Update coverage script to use nyc
- [x] Ignore the auto-generated nyc output

### Next Steps

- [x] Get insight into how we use Codecov to make sure this doesn't break anything

cc @mapbox/geocoding-gang

### CODE REVIEW

**Comment by boblannon** [comment]
I'm not sure this is working properly.  for whatever reason, the checks for codecov.io aren't being triggered on this PR.  compare with #691:

2018-03-22 at 2 15 pm

Looking at [the codecov dashboard](https://codecov.io/gh/mapbox/carmen/commit/5ef23361d7904002d146eed07cd444c1902f61d1), I think it's having trouble parsing what you're giving it:

2018-03-22 at 2 16 pm

i think we're going to want something more similar to the example that codecov [has in their docs](https://github.com/codecov/example-node#nyc):

```
nyc report --reporter=text-lcov > coverage.lcov && codecov",
```

**Comment by boblannon** [comment]
looking at the nyc docs, it seems like you might just be able to add the `--reporter` flag to the `nyc` invocation itself, so you'd have 

```
TESTING=true nyc --reporter=lcov --reporter=text-lcov tape test/*.js && codecov
```

**Comment by Nmargolis** [comment]
thanks! I'm going to try pushing that up and seeing if it works.

**Comment by boblannon** [comment]
2018-03-26 at 9 41 pm

overiding to merge.  the difference here seems related to how istanbul and nyc calculate coverage.

**Pull request merged**
