### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by aarthykc**
### Context
- [x] README has CI status badge
- [x] package.json includes as devDependencies (see https://github.com/mapbox/eslint-config-geocoding/)
  - eslint
  - eslint-node-plugin
  - @mapbox/eslint-config-geocoding
- [x] .eslintrc or package.json@eslintConfig configured to use @mapbox/eslint-config-geocoding
- [x] Project includes script for npm test and npm lint
- [x] npm lint runs eslint, runs on both library JS files and test JS files
- [x] npm test runs eslint, runs on both library JS files and test JS files
- [x] npm test run includes nyc --check-coverage, defines thresholds for pass/fail
- [x] Uses travis or circle for CI, uses node >= 6.x
- [ ] Tests pass

### Next Steps
- [ ] Work through the list^

cc @mapbox/geocoding-gang
@boblannon

### CODE REVIEW

**Comment by boblannon** [comment]
here's a list of files ranked by the number of eslint errors.  should make it easier to split up the work.  i can try and get an even split but it's a pretty long tail, so i think if we just split the heavy files we should be good:

| path                                                        |     num_count |
| ----------------------------------------------------------- | ----- |
| /carmen/lib/util/remove-diacritics.js                       | 1,899 |
| /carmen/test/address.test.js                                | 1,069 |
| /carmen/test/replace.test.js                                |   457 |
| /carmen/test/termops.getIndexableText.test.js               |   311 |
| /carmen/test/context.test.js                                |   230 |
| /carmen/test/indexdocs.test.js                              |   203 |
| /carmen/test/ops.test.js                                    |   151 |
| /carmen/lib/verifymatch.js                                  |   146 |
| /carmen/lib/indexer/indexdocs.js                            |   138 |
| /carmen/lib/merge.js                                        |   137 |
| /carmen/lib/util/closest-lang.js                            |   134 |
| /carmen/lib/util/termops.js                                 |   133 |
| /carmen/lib/context.js                                      |   104 |
| /carmen/test/geocode-unit.address-format.test.js            |    96 |
| /carmen/lib/pure/addressitp.js                              |    94 |
| /carmen/test/spatialmatch.stackable.test.js                 |    84 |
| /carmen/test/index.test.js                                  |    81 |
| /carmen/test/geocode-unit.address-misc.test.js              |    78 |
| /carmen/test/index.merge-norm.test.js                       |    77 |
| /carmen/lib/geocode.js                                      |    77 |
| /carmen/index.js                                            |    76 |
| /carmen/lib/util/ops.js                                     |    75 |
| /carmen/lib/util/feature.js                                 |    73 |
| /carmen/lib/spatialmatch.js                                 |    73 |
| /carmen/lib/util/dawg.js                                    |    63 |
| /carmen/test/geocode-unit.tokens.test.js                    |    59 |
| /carmen/lib/util/token.js                                   |    57 |
| /carmen/lib/index.js                                        |    55 |
| /carmen/test/index.merge.test.js                            |    54 |
| /carmen/test/bin.test.js                                    |    45 |
| /carmen/test/verifymatch.test.js                            |    44 |
| /carmen/test/token.test.js                                  |    43 |
| /carmen/test/geocode-unit.address-alphanumeric.test.js      |    42 |
| /carmen/lib/phrasematch.js                                  |    41 |
| /carmen/lib/pure/addresscluster.js                          |    39 |
| /carmen/lib/copy.js                                         |    38 |
| /carmen/test/index.multimerge.test.js                       |    34 |
| /carmen/lib/merge-worker.js                                 |    31 |
| /carmen/test/cache.test.js                                  |    31 |
| /carmen/test/geocode-unit.order.test.js                     |    31 |
| /carmen/lib/api-mem.js                                      |    30 |
| /carmen/scripts/carmen-index.js                             |    30 |
| /carmen/scripts/carmen.js                                   |    29 |
| /carmen/scripts/carmen-merge.js                             |    28 |
| /carmen/test/termops.getIndexablePhrases.test.js            |    27 |
| /carmen/test/geocode-unit.bbox-antimeridian.test.js         |    27 |
| /carmen/test/feature.putFeatures.test.js                    |    25 |
| /carmen/test/geocode-unit.geocoder_type.test.js             |    25 |
| /carmen/test/geocode-unit.fallback.test.js                  |    24 |
| /carmen/lib/util/addfeature.js                              |    24 |
| /carmen/test/geocode-unit.promote-on-identical-name.test.js |    23 |
| /carmen/test/diacritics.test.js                             |    22 |
| /carmen/test/geocode-unit.score.test.js                     |    22 |
| /carmen/test/geocode-unit.languageFallback.test.js          |    21 |
| /carmen/test/termops.maskAddress.test.js                    |    21 |
| /carmen/test/geocode-unit.localtext.test.js                 |    20 |
| /carmen/test/geocode-unit.geocoder_stack.test.js            |    19 |
| /carmen/lib/util/filter.js                                  |    19 |
| /carmen/test/geocode-unit.reverse-scoredist.test.js         |    18 |
| /carmen/test/indexdocs.parseDocs.test.js                    |    18 |
| /carmen/test/geocode-unit.relevance.test.js                 |    17 |
| /carmen/test/geocode-unit.language-universal.test.js        |    17 |
| /carmen/test/geocode-unit.index-context.test.js             |    16 |
| /carmen/test/geocode-unit.jp-order.test.js                  |    16 |
| /carmen/test/termops.encodePhrase.test.js                   |    16 |
| /carmen/lib/util/permute.js                                 |    16 |
| /carmen/test/geocode-unit.translation-noauto.test.js        |    16 |
| /carmen/test/addfeature.test.js                             |    16 |
| /carmen/test/geocode-unit.multitype.test.js                 |    15 |
| /carmen/test/geocode-unit.multitype-reverse.test.js         |    15 |
| /carmen/test/geocode-unit.dataterm-vs-postcode.test.js      |    14 |
| /carmen/test/geocode-unit.language-flag.test.js             |    13 |
| /carmen/lib/analyze.js                                      |    13 |
| /carmen/test/geocode-unit.proximity.test.js                 |    13 |
| /carmen/test/geocode-unit.address-omitted.test.js           |    13 |
| /carmen/test/dawgcache.test.js                              |    13 |
| /carmen/test/geocode-unit.types.test.js                     |    13 |
| /carmen/test/geocode-unit.limit.test.js                     |    13 |
| /carmen/lib/util/proximity.js                               |    12 |
| /carmen/test/spatialmatch.rebalance.test.js                 |    12 |
| /carmen/test/geocode-unit.proximity-polygon.test.js         |    12 |
| /carmen/test/termops.encodeTerm.test.js                     |    12 |
| /carmen/test/termops.id.test.js                             |    12 |
| /carmen/test/geocode-unit.language-flag-reverse.test.js     |    11 |
| /carmen/test/geocode-unit.bbox.test.js                      |    11 |
| /carmen/test/proximity.scoredist.test.js                    |    11 |
| /carmen/test/geocode-unit.jp-numeric.test.js                |    11 |
| /carmen/test/termops.getHousenumRangeV3.test.js             |    11 |
| /carmen/test/address.nearest.test.js                        |    11 |
| /carmen/lib/util/dedupe.js                                  |    11 |
| /carmen/test/geocode-unit.context-overlap.test.js           |    10 |
| /carmen/test/index.merge.bench.test.js                      |    10 |
| /carmen/lib/util/cxxcache.js                                |    10 |
| /carmen/test/index.bbox.test.js                             |     9 |
| /carmen/test/geocode-unit.address-numnum.test.js            |     9 |
| /carmen/test/geocode-unit.io-stack.test.js                  |     9 |
| /carmen/test/filter.test.js                                 |     9 |
| /carmen/test/geocode-unit.invalid-tokens.test.js            |     9 |
| /carmen/test/geocode-unit.cluster-vs-range.test.js          |     8 |
| /carmen/lib/util/grid.js                                    |     8 |
| /carmen/test/geocode-unit.scoresort.test.js                 |     8 |
| /carmen/test/geocode-unit.spatialmatch.test.js              |     8 |
| /carmen/test/termops.tokenize.test.js                       |     8 |
| /carmen/test/geocode-unit.address-bitmask.test.js           |     7 |
| /carmen/test/fixtures/tokens.js                             |     7 |
| /carmen/test/bbox.intersect.test.js                         |     7 |
| /carmen/test/bbox.inside-box.test.js                        |     7 |
| /carmen/scripts/carmen-copy.js                              |     7 |
| /carmen/test/geocode-unit.backy.test.js                     |     7 |
| /carmen/test/geocode-unit.bmask.test.js                     |     7 |
| /carmen/test/geocode-unit.debug.test.js                     |     7 |
| /carmen/test/geocode-unit.io-autocomplete.test.js           |     7 |
| /carmen/test/geocode-unit.unidecollide.test.js              |     7 |
| /carmen/test/geocode-unit.multitype-leapfrog.test.js        |     7 |
| /carmen/test/geocode-unit.name-conflict.test.js             |     7 |
| /carmen/test/geocode-unit.range.test.js                     |     7 |
| /carmen/test/geocode-unit.noauto.test.js                    |     6 |
| /carmen/test/geocode-unit.index-limit.test.js               |     6 |
| /carmen/test/geocode-unit.lowrelev.test.js                  |     6 |
| /carmen/test/geocode-unit.gappy.test.js                     |     6 |
| /carmen/test/geocode-unit.address-vs-postcode.test.js       |     6 |
| /carmen/test/termops.permutations.test.js                   |     5 |
| /carmen/test/geocode-unit.tile-edge.test.js                 |     5 |
| /carmen/test/geocode-unit.stacky.test.js                    |     5 |
| /carmen/test/geocode-unit.duplicate-address.test.js         |     5 |
| /carmen/test/termops.getWeights.test.js                     |     5 |
| /carmen/test/geocode-unit.numeric.test.js                   |     5 |
| /carmen/test/geocode-unit.named.test.js                     |     5 |
| /carmen/test/geocode-unit.dataterm.test.js                  |     5 |
| /carmen/test/geocode-unit.matching-text.test.js             |     5 |
| /carmen/test/bbox.xyz.test.js                               |     5 |
| /carmen/test/geocode-unit.zeroscore.test.js                 |     4 |
| /carmen/test/permute.test.js                                |     4 |
| /carmen/lib/util/uniq.js                                    |     4 |
| /carmen/test/geocode-unit.numeric-address.test.js           |     4 |
| /carmen/test/output.test.js                                 |     4 |
| /carmen/test/geocode-unit.dataterm-only.test.js             |     4 |
| /carmen/test/geocode-unit.early-degen.test.js               |     4 |
| /carmen/test/geocode-unit.language-flag-bogus.test.js       |     4 |
| /carmen/test/geocode-unit.scorefactor.test.js               |     3 |
| /carmen/test/feature.test.js                                |     3 |
| /carmen/lib/util/bbox.js                                    |     3 |
| /carmen/test/geocode-unit.multilanguage.test.js             |     3 |
| /carmen/test/grid.test.js                                   |     3 |
| /carmen/scripts/tokenize.js                                 |     3 |
| /carmen/test/dedupe.test.js                                 |     3 |
| /carmen/test/geocode-unit.unicode.test.js                   |     3 |
| /carmen/scripts/carmen-analyze.js                           |     3 |
| /carmen/lib/loader.js                                       |     3 |
| /carmen/test/termops.terms.test.js                          |     3 |
| /carmen/test/closest-lang.test.js                           |     2 |
| /carmen/test/geocode-unit.unicode-replace.test.js           |     2 |
| /carmen/test/geocode-unit.featurenoop.test.js               |     2 |
| /carmen/test/geocode-unit.text-trim.test.js                 |     2 |
| /carmen/test/termops.uniqPermutations.test.js               |     2 |
| /carmen/test/geocode-unit.emoji-bomb.test.js                |     2 |
| /carmen/test/geocode-unit.multiconfig.test.js               |     2 |
| /carmen/test/geocode-unit.dict-collision.test.js            |     2 |
| /carmen/test/termops.numTokenV3.test.js                     |     1 |
| /carmen/lib/constants.js                                    |     1 |
| /carmen/test/proximity.test.js                              |     1 |
| /carmen/test/termops.parseSemiNumber.test.js                |     1 |
| /carmen/test/termops.numTokenize.test.js                    |     1 |
| /carmen/test/termops.encodableText.test.js                  |     1 |
| /carmen/test/geocode-unit.emoji.test.js                     |     1 |
| /carmen/test/geocode-unit.languageMode.test.js              |     1 |
| /carmen/test/termops.numTokenV2.test.js                     |     1 |
| /carmen/test/geocode-unit.strictloose.test.js               |     1 |
| /carmen/test/context.stackFeatures.test.js                  |     1 |
| /carmen/test/geocode-unit.languageMode-universal.test.js    |     1 |
| /carmen/test/geocode-unit.multiload.test.js                 |     1 |
| /carmen/test/copy.test.js                                   |     1 |
| /carmen/test/geocode-unit.byid.test.js                      |     1 |
| /carmen/test/geocode-unit.konglish.test.js                  |     1 |
| /carmen/test/fallback.test.js                               |     1 |
| /carmen/test/geocode-unit.io-reverse.test.js                |     1 |
| /carmen/test/geocode-unit.promote-language.test.js          |     1 |
| /carmen/test/termops.isAddressNumber.test.js                |     1 |
| /carmen/test/geocode-unit.promote-score.test.js             |     1 |
| /carmen/test/uniq.test.js                                   |     1 |
| /carmen/test/termops.logScale3Bit.test.js                   |     1 |
| /carmen/test/geocode-unit.scoredist.test.js                 |     1 |
| /carmen/test/geocode-unit.fnv1a-collision.test.js           |     1 |
| /carmen/test/legacy.test.js                                 |     1 |

**Comment by apendleton** [comment]
So... this diff is (unsurprisingly) a bit overwhelming. I'm wondering if you might have a sec to highlight any changes that were more substantive than just `s/var/let/` ? We can skim the whole thing, but I don't want to miss anything.

**Comment by boblannon** [comment]
yeah i made a point of isolating some commits that were more substantial changes:



[variable renaming](https://github.com/mapbox/carmen/pull/686/commits/7efda48e79e0eff4d6c34cf34bdb22e73f1ca965)

[moving eslintrc](https://github.com/mapbox/carmen/pull/686/commits/93db4d0835f491bda7b80276f120c4e104c311bb)

is it worth moving data out of [remove-diacritics](https://github.com/mapbox/carmen/pull/686/commits/cd80391d4db291540e751c1bf5b2c3f88aec4c81) into separate json files?

@apendleton you gave me feedback on [this awkward change](https://github.com/mapbox/carmen/pull/686/commits/14a69ce5541b3351fe6260cdd24678f6fd4bb0a1) already, and i'll most likely take your advice.

no idea what [rpad](https://github.com/mapbox/carmen/pull/686/commits/5c6037f17b37cb84f33a2da606ce6a024edbb5d5) was for. linter complained that it wasn't used.

**Comment by aarthykc** [comment]
@apendleton yeah for sure, this diff is rather overwhelming. The kinds of liniting issues that I came across and (@boblannon please add your thoughts too) were:
- Using const or let instead of var 
- Changing `function(err)` to `((err) =>)` 
- Adding `'use strict'` to each file
- Changing `==` to `===` and `!=` to `!==`
- There were no spaces before `}` in some places

 I also added the circleci badge in an initial commit, but other than that, it's mostly these changes^

**Comment by apendleton** [comment]
Actually I got mixed up about who's reviewing what. Thanks for your feedback though, and hopefully your actual reviewers will find it useful 😄

**Comment by boblannon** [comment]
cc @samely @ingalls for review :)

**Pull request merged**
