### PR TITLE
[dnm] refactor verifymatch scoredist implementation

### PR DESCRIPTION
**Pull request by lizziegooding**
### Context

With proximity enabled, we should consider distance from the proximity point as well as feature prominence when deciding the order of results to return to users. The simplest way to implement a score that's a composite of two factors is to scale each factor to a bounded range of values and combine them either by multiplying or subtracting. If they're of the same importance, we would bound them to the same scale, say 0 - 1, and if they're of different importances, we can manipulate that scale so the more important factor is scaled to a higher range of vales than the less important factor. 

For our implementation, `score` is already scaled roughly along an exponential curve. I started experimenting with reducing `score` to the point where it can be compared along roughly the same scale (but not necessarily the same curve) as `distance` and multiplying the product of those values. I scaled distance along a very extreme curve (hyperbola `y = 1/x`) where as the distance approaches 0, `y` approaches `∞` The distance is scaled by the proximity bias radius to extend the bias for larger features that are higher on the admin hierarchy. Because I'm combining with multiplication, the minimum value for either value is 1. If the feature is beyond the bias radius, the distance weighting defaults to 1 so these features are only sorted by score.

Here's an example of the affect this change has had on sort order for a particular test case, querying `missi` near the Mission in San Francisco:

| order | master                                                      | proximity-algorithm                                         |
|-------|-------------------------------------------------------------|-------------------------------------------------------------|
| 1     | Mississippi                                                 | Mission                                                     |
| 2     | Mission                                                     | Mission Branch Library                                      |
| 3     | Mission Branch Library                                      | Mission Wishing Tree                                        |
| 4     | Mission Wishing Tree                                        | Mission Pie,cafe, coffee, tea, tea house                    |
| 5     | Mission's Kitchen,fast food                                 | Mission's Kitchen,fast food                                 |
| 6     | Mission Cultural Center for Latino Arts,college, university | Mission Terrace                                             |
| 7     | Mission Pie,cafe, coffee, tea, tea house                    | Mission Bay                                                 |
| 8     | Mission Critter                                             | Mission Cultural Center for Latino Arts,college, university |
| 9     | Mission Gastroclub                                          | Mission Critter                                             |
| 10    | Mission Tires & Service Center                              | Mission Gastroclub                                          |
| 11    | Mission Skateboards                                         | Mission Tires & Service Center                              |
| 12    | Mission Dental Care                                         | Mission Skateboards                                         |
| 13    | Mission Pet Hospital                                        | Mission Dental Care                                         |
| 14    | Mission Terrace                                             | Mission Pet Hospital                                        |
| 15    | Mission Bay                                                 | Mission Workshop,bicycle, bike, cycle                       |
| 16    | Mission Workshop,bicycle, bike, cycle                       | Mission-Foothill                                            |
| 17    | Mission Bay Mobile Home Park                                | Mission Bay Mobile Home Park                                |
| 18    | Mission-Foothill                                            | Mississippi                                                 |
| 19    | Mission District                                            | Mission Dolores                                             |
| 20    | Mission Dolores                                             | Mission District                                            |

The order of results is:
- very proximate prominent features (e.g.`Mission` neighborhood)
- very proximate non-prominent features (e.g. `Mission Branch Library`)
- somewhat proximate prominent features (e.g. `Mission Bay` neighborhood)
- somewhat proximate non-prominent features (e.g. `Mission Workshop,bicycle, bike, cycle`)
- distant, prominent features (e.g. `Mississippi`)

From initial testing, it seems that the curves I've chosen to start may be too extreme. I'm guessing I may be weighing distance too much over score and a distance value that can actually approach ∞ is not tenable. I'm going to experiment with 1) tweaking the existing curves 2) bounding max possible values 3) altering the bias radius we calculate per zoom level.

### Summary of Changes
- [ ] scale `carmen:score` along a logarithmic curve
- [ ] scale the distance as a proportion of the bias radius along a hyperbola
- [ ] add tests for `missi` query near Mission neighborhood in San Francisco

### Next Steps
- [ ] test against downstream passrates
- [ ] get tests to pass on this branch
- [ ] continue experimenting

cc @miccolis @aarthykc @apendleton @boblannon

### CODE REVIEW

**Comment by boblannon** [comment]
this looks super promising!  nice work 🌵

**Comment by aarthykc** [comment]
Looks great @lizziegooding !

**Comment by lizziegooding** [comment]
When testing this against downstream acceptance tests, I noticed that the order of results returned by my new `scoredist` implementation was not the same as the order returned in the final response. This changed between the `sortFeature` and `sortContext` functions

After `sortFeature`:
```
index  name                  dist    distVal    score  scoreVal  scoredist
-----  --------------------  ------  ---------  -----  --------  ----------
1.     Mission               0.1694  3540.8866  609    6.4135    22709.4762
2.     Mission Bay           1.5466  387.9502   46     3.8501    1493.6471
3.     Mission Dolores Park  0.5638  354.7353   54     4.0073    1421.5308
4.     Mission Cheese,beer,  0.3132  638.6130   4      1.6094    1027.7838
5.     Mission Terrace       2.6585  225.6909   50     3.9318    887.3715
```

After `sortContext`:
```
index  name                  dist    distVal    score  scoreVal  scoredist   relev  scoredistAgain
-----  --------------------  ------  ---------  -----  --------  ----------  -----  --------------
1.     Mission Terrace       2.6585  225.6909   50     3.9318    887.3715    1      887.3715
2.     Mission Bicycle Comp  0.3069  651.7114   1      1         651.7114    1      651.7114
3.     Mission Cycling       0.3151  634.6565   0      1         634.6565    1      634.6565
4.     Mission Cycling Satu  0.3235  618.2162   0      1         618.2162    1      618.2162
5.     Mission Playground S  0.3354  596.2201   0      1         596.2201    1      596.2201
```

Both functions sort by `scoredist`, which hadn't changed between when each sort was invoked. I did not observe this behavior on master.

After some digging, I found that in my implementation, `scoredist` was being stored as a string rather than a number. Like master, this implementation rounds the final scoredist value and returns it as a string using `toFixed()`. 
https://github.com/mapbox/carmen/blob/2d2b0438cb85057d20e6ebc18ea556433d5795af/lib/util/proximity.js#L89

However, on master, we take the `Math.max()` of either the `scoredist` and the `score`. This converts the final value stored in `carmen:scoredist` to a number _even if the string `scoredist` > `score`_.

https://github.com/mapbox/carmen/blob/2d2b0438cb85057d20e6ebc18ea556433d5795af/lib/geocoder/verifymatch.js#L200-L203

To account for this, I changed the `scoredist` function to convert the rounded `toFixed()` string to a number.

**Comment by lizziegooding** [comment]
I was wrong! As @apendleton pointed out, the implementation on master is to convert to a number (`parseFloat`) after rounding (`toFixed`): https://github.com/mapbox/carmen/blob/2d2b0438cb85057d20e6ebc18ea556433d5795af/lib/util/proximity.js#L89

Whereas my implementation was to parse the products as floats and then round:
https://github.com/mapbox/carmen/blob/ab3ebd27109d3b26442103b0a4f8fb72eae38948/lib/util/proximity.js#L85

**Comment by lizziegooding** [comment]
Not going with this approach, moved to https://github.com/mapbox/carmen/pull/768

**Pull request closed without merging**
