### PR TITLE
Rebalance stacks earlier in the algorithm.

### PR DESCRIPTION
**Pull request by arunasank**

### CODE REVIEW

**Comment by arunasank** [comment]
Tested the new relevance logic against a bunch of fixtures:

```
-71.3825511932373,41.8787000494442,Margosa Road Pawtucket United States
-81.9497680664062,28.0394857970299,Mahatma Gandhi Road Lakeland United States
-119.78479385376,36.7394343794487,Downing Street Fresno United States
-101.833820343018,35.207197008288,Nelson Mandela Road Amarillo United States
-106.313066482544,42.8666543236458,German-American heritage Museum Casper United States
-77.4019432067871,37.2279364765097,Veracruz de Ignacio de la Llave Petersburg United States
-122.272853851318,37.8708559899998,Seine-et-Marne Berkeley United States
-84.2809295654297,30.4380920748054,Seine-Port Tallahassee United States
-111.899271011353,33.5091246717203,Vaticano Boyaca Scottsdale United States
-73.2007026672363,40.8559548019455,Benda Banten Smithtown United States
```
`carmen` geocodes as expected, i.e relevance is computed according to indexes that match without any bonus for the lengths of strings in each index.

**Comment by arunasank** [comment]
@yhahn Can you take a final :eyes: before we merge?

**Comment by yhahn** [comment]
@arunasank :joy: :+1: Do you want to:

- Clean up the debugging `console.log()` calls,
- Update comments/remove TODO comments.

Then we can go through the release process : )

**Comment by arunasank** [comment]
@yhahn done! \o/

**Comment by arunasank** [comment]
[Documentation](https://gist.github.com/arunasank/22fcec460bfe648013ff) for the rebalancing quest.

**Comment by sbma44** [comment]
what else needs to happen here prior to merge?

**Comment by yhahn** [comment]
@arunasank this looks awesome and your stats from IRL testing are :heart_eyes:

:ship: at will!

- [ ] merge into master
- [ ] changelog entry
- [ ] bump package.json
  - commit
  - tag and push tag to github
- [ ] npm publish

cc @mapbox/geocoding-gang

**Comment by arunasank** [comment]
@yhahn Done and done! Thanks, sensei. :bow:

**Pull request merged**
