### PR TITLE
Point to mapnik v2_spec

### PR DESCRIPTION
**Pull request by jakepruitt**
cc/ @mapsam @springmeyer @flippmoke 

refs https://github.com/mapbox/mapnik-swoop/pull/10

### CODE REVIEW

**Comment by springmeyer** [comment]
@jakepruitt - this is failing because carmen is still using `vt.parse`. This struct me as odd as I thought I already removed this from carmen, but https://github.com/mapbox/carmen/pull/332/files was never merged. I will work with ingalls to get https://github.com/mapbox/carmen/pull/332/files into master first, then we can rebase this branch.

**Comment by jakepruitt** [comment]
:+1: Awesome, thanks Dane.

**Comment by springmeyer** [comment]
@jakepruitt - thanks for the patience - all clear now: #332 is merged and I've rebased. We'll see what travis says now :)

**Comment by springmeyer** [comment]
Just rebased this and it is ready to merge. This will bring significant speedups in vtile parsing:

### Master / node-mapnik 3.4.16

```
$ node bench/contextVector.js 
context vector x 274 ops/sec ±2.12% (87 runs sampled)
Memory -> peak rss: 57466880 / peak heap: 20806432
```

### This branch / node-mapnik 3.5.12

```
$ node bench/contextVector.js 
context vector x 348 ops/sec ±0.34% (86 runs sampled)
Memory -> peak rss: 58699776 / peak heap: 22004080
```

**Pull request merged**
