### PR TITLE
Reduce address cluster memory usage

### PR DESCRIPTION
**Pull request by tmcw**
This method was keeping an array in memory but only using a minimum
value. Minimum can be calculated online, so let's do that and avoid
requiring any more memory.

### CODE REVIEW

**Comment by ingalls** [comment]
This looks awesome! :+1:

**Comment by sbma44** [comment]
any reason not to merge @ingalls?

**Comment by ingalls** [comment]
Yeah I'm good on this crossing the finish line as long as @tmcw is finished with the branch

**Comment by tmcw** [comment]
Yep, I'm done w/ this branch

**Pull request merged**
