### PR TITLE
Fix benchmarks

### PR DESCRIPTION
**Pull request by springmeyer**
### Context

I've found that most of the scripts inside `bench/` are broken due to various changes which regressed them. This PR attempts to fix them to get them all working again.

### Next Steps

The `bench/phrasematch.js` script is segfaulting (in `carmen::cache::has`) for me locally. Looks like some kind of infinite loop is happening.

### CODE REVIEW

**Comment by mattficke** [comment]
@springmeyer Thanks for taking this on. One important thing to note is that we don't check for passing bench test on Circle. Even if we don't want to rigorously check the benchmark _values_ on each run, we may want to at least check that the benchmark tests run without errors to avoid regressions like this in the future.

**Comment by springmeyer** [comment]
Remaining needs are:

  - Updating the indexing benchmarks. It looks like @ingalls may have tried to do this in https://github.com/mapbox/carmen/commit/ba6ef640cdc27a0c685ea9af599c0386939ba8e5 but missed the actual API changes, which are significant.
  - Getting things passing on circle to prevent regressions.

**Comment by springmeyer** [comment]
Remaining failures:

```
Running bench/index.indexdocs.js
/home/ubuntu/carmen/bench/index.indexdocs.js:8
var freq = index.generateFrequency(docs, {});
                 ^

TypeError: index.generateFrequency is not a function
    at Object.<anonymous> (/home/ubuntu/carmen/bench/index.indexdocs.js:8:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
***** ERROR: bench/index.indexdocs.js failed to run *****
Running bench/index.loadDoc.js
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/indexer/indexdocs-worker.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/carmen/bench/index.loadDoc.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by springmeyer** [comment]
Thanks for landing @yhahn

**Pull request merged**
