### PR TITLE
Doff thy name unidecode cxx

### PR DESCRIPTION
**Pull request by apendleton**
@camilleanne here are the changes to use the cxx version of unidecode (though it should probably go onto npm at some point)

### CODE REVIEW

**Comment by apendleton** [comment]
Okay, I think this is good to go

**Comment by yhahn** [comment]
:ship: (minor version bump since there's a dep change?)

**Comment by apendleton** [comment]
@yhahn we're already behind master version-wise (8.1.0 in this branch vs. 8.1.1 in master). Do I skip ahead to 8.1.2?

**Comment by camilleanne** [comment]
@apendleton :shipit:

**Pull request merged**
