### PR TITLE
[W, S, E, N] bbox order

### PR DESCRIPTION
**Pull request by mattficke**
### Context
A bounding box property in included for features with polygon geometry, formatted in `[minX, minY, maxX, maxY]` coordinate order. When feature polygons include coordinates close to and on both sides of the anti-meridian (such as Russia, the United States, Fiji, and others), the resulting bounding box spans nearly the entire width of the world.

In these situations we should return the smaller of the two possible bounding boxes, and allow coordinates to be ordered `[W, S, E, N]` rather than `[minX, minY, maxX, maxY]`.

refs https://github.com/mapbox/carmen/issues/574

### Summary of Changes
* Generate anti-meridian crossing bboxes for features that straddle the dateline

### Next Steps
- [x] Still need to add a backwards-compatible migration function to optionally clip anti-meridian crossing bboxes at +-180 degreees

Also note that this does not change the bbox query parameter, which still only accepts bboxes in `[minX, minY, maxX, maxY]` order.

cc @mapbox/geocoding-gang @brsbl

### CODE REVIEW

**Comment by mattficke** [comment]
I think this is ready to go, though I'd like another set of eyes on the clipping section in particular to make sure this approach is a good one. I made anti-meridian clipping the default behavior, which you can turn off with an options setting.

**Comment by mattficke** [comment]
>Rather than making clipBBox an index-time option, could this be done at runtime and applied at the final step of returning features?

This is done.

**Comment by 1ec5** [comment]
This PR turns out to be consistent with the terminology used [in MapboxGeocoder.swift](https://github.com/mapbox/MapboxGeocoder.swift/blob/6a4645bf8b19a1cb3703894141fc1bfe5d316d12/MapboxGeocoder/MBPlacemark.swift#L390-L392). 👍

**Comment by mattficke** [comment]
@1ec5 glad to hear it! Out of curiosity, how would `RectangularRegion` handle antimeridian-crossing situations? Our current implementation ensures that this doesn't happen in practice, but it's possible this will change in a future API version.

**Comment by 1ec5** [comment]
[The documentation](https://github.com/mapbox/MapboxGeocoder.swift/blob/b55d3f1bf0985d8a43098c8bf97a4eb2153bd626/MapboxGeocoder/MBRectangularRegion.swift#L14) currently says:

> `southWest` must be to the southwest of `northEast`. The region may not span the antimeridian. If you need to restrict a query to a region that spans the antimeridian, such as the region that encompasses Fiji, perform two queries each limited to the region on either side of the antimeridian, then combine the results.

MapboxGeocoder.swift has yet to reach v1.0, so we’re free to relax the prohibition against spanning the antimeridian at any point. As a developer, I’d expect to be able to provide a single bbox that straddles the antimeridian in the request or get a similar bbox in the response. That’s how the Mapbox GL libraries work (including the iOS and macOS SDKs). Do we have a ticket tracking antimeridian-straddling bboxes in requests?

**Pull request merged**
